services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: science
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_docker_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  nodeapp:
    image: node_science
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - .:/app
    working_dir: /app
    command: node index.mjs

volumes:
  postgres_docker_data: